Config added
mixanemca/example-gorilla-rest-api pull request #2
Opened 2023-09-03 08:13 UTC by 0ylo

2023-09-03 09:10 UTC, nemca requested changes

2023-09-03 09:10 UTC, nemca commented on README.md
> +### Create postgresDB in docker
Какой отношение это имеет к Config? Надо выносить в отдельный коммит

2023-09-03 09:10 UTC, nemca commented on README.md
> +### Create postgresDB in docker
Имена собственные пишутся с заглавной буквы - PostgreSQL, Docker.

2023-09-03 09:10 UTC, nemca commented on README.md
> +##### For create migration, use this command in 'migration' folder
Зачем здесь заголовок? Вроде обычный абзац.

2023-09-03 09:10 UTC, nemca commented on README.md
> + goose create add_updated_at
Надо добавить, что для миграций используется инструмент `goose`. И ссылку на документацию и как установить.

2023-09-03 09:10 UTC, nemca commented on cmd/main.go
> +package main
`cmd/main.go` хорошо, но лучше убирать чуть глубже в `cmd/example-gorilla-rest-api/main.go`.

2023-09-03 09:10 UTC, nemca commented on internal/config/config.go
> +	"github.com/ilyakaznacheev/cleanenv"
Я бы предпочел использовать `viper`.

2023-09-03 09:10 UTC, nemca commented on config/config.yaml
> +http_server:
У нас нет клиента, так что лучше и лаконичнее
```
http:
  address: "127.0.0.1:8080"
  timeout:
    read: 5s
    write: 5s
```

2023-09-03 09:10 UTC, nemca commented on config/config.yaml
> +env: "local"
Это зачем?

2023-09-03 09:10 UTC, nemca commented on internal/config/config.go
> +		log.Fatal("CONFIG_PATH is not set")
Надо возвращать ошибку, а не падать с `log.Fatal`. Оставь обработку на верхний уровень.

2023-09-03 09:10 UTC, nemca commented on internal/config/config.go
> +	configPath := os.Getenv("CONFIG_PATH")
Если уж взялся делать переменные окружения, то хорошо бы префикс отдельный делать. А то получится скоро, что у тебя будет несколько программ с переменной `CONFIG_PATH`.
Ну и с первого взгляда в условный bashrc вообще не понятно к чему относится `CONFIG_PATH`.

2023-09-03 09:10 UTC, nemca commented on internal/config/config.go
> +	configPath := os.Getenv("CONFIG_PATH")
Конфиг должен настраиваться через флаг `-c`, `--config` и иметь дефолт

2023-09-03 09:10 UTC, nemca commented on cmd/main.go
> +	fmt.Println(cfg)
Лайвхак
```go
_ = cfg
```

2023-09-03 09:10 UTC, nemca commented on cmd/main.go
> +	// Init config
Комментарий от капитана.
Давай либо писать что-то более внятное, либо вообще не писать, потому что на следующей строчке `config.InitConfig()` вообще не двусмысленно.
А еще точку в конце предложения ставить надо :)

2023-09-06 13:22 UTC, 0ylo commented on config/config.yaml
> +env: "local"
Переключать с локальной среды на тест и прод, чтобы менять уровень логирования с дебаг на инфо

2023-09-06 15:36 UTC, 0ylo commented on internal/config/config.go
> +	configPath := os.Getenv("CONFIG_PATH")
это через 
flag.StringVar()
flag.Parse()

задавать путь к ямл файлу в довесок к viper.AddConfigPath()?

2023-09-09 11:55 UTC, nemca requested changes

2023-09-09 11:55 UTC, nemca commented on internal/logger/logger.go
> +	envLocal = "local"
Не надо нам.
Пусть будут уровни логирования, как в самом `slog` - error, warning, info. debug...

2023-09-09 11:55 UTC, nemca commented on internal/logger/logger.go
> +	case envLocal:
А тут кажется проще распарсить 1 раз уровень логирования + формат лога (текст или json) и 1 раз создать логгер

2023-09-19 08:12 UTC, nemca requested changes

2023-09-19 08:12 UTC, nemca commented on README.md
> +# how to set logger level & format(text or json):
Не, лучше просто `--help` прикладывать. И никогда не писать в README `go run`.

2023-09-19 08:12 UTC, nemca commented on configs/example-gorilla-rest-api.yaml
> +  level: debug
Пиши или все строки в кавычках или без.

2023-09-19 08:12 UTC, nemca commented on go.mod
> +go 1.20
>The new log/slog package in Go 1.21 brings structured logging to the standard library.

И по этому у тебя экспорт не из стандартной библиотеке, а из `golang.org/x/exp/slog`

2023-09-19 08:12 UTC, nemca commented on internal/config/config.go
> +	Password string
А здесь почему нет тегов?

2023-09-19 08:12 UTC, nemca commented on internal/config/config.go
> +	// save DB pass from enviroment to Struct
Что-то странное.
Давай делать, как обычно - пароль или в конфиге или в флагах или в переменных окружения.
И назначать надо не через Lookup или Get, а через биндинг

2023-09-19 08:12 UTC, nemca commented on internal/config/config.go
> +	Format string `mapstructure:"format"`
Зачем тебе тут строка в `Level`? Надо юзать тип `slog.Level`

2023-09-19 08:12 UTC, nemca commented on internal/logger/logger.go
> +	case "debug":
Принимай сразу уровень в виде `slog.Level`

```
func New(level slog.Level, format string) *slog.Logger
```

и тогда не придется напихивать ужасных switch-case конструкций.

2023-09-21 13:41 UTC, nemca commented on configs/example-gorilla-rest-api.yaml
> +http-config:
Просто http

2023-09-21 13:48 UTC, nemca commented on internal/config/config.go
> +	viper.SetConfigName("example-gorilla-rest-api")
config.yaml

2023-09-21 14:05 UTC, nemca commented on internal/config/config.go
> +	Level  string `mapstructure:"level"`
```
Level slog.Level
```

2023-09-22 06:31 UTC, nemca commented on README.md
> +# how to set logger level & format(text or json):
Пока не исправил не убирай, пожалуйста, в resolve

2023-09-22 06:32 UTC, nemca commented on configs/config.yaml
> +  level: -4
Ну вот ты сам вспомнишь через неделю, что такое `-4`?
Надо делать, как у людей - `info`, `warning`, etc...

2023-09-22 06:35 UTC, 0ylo commented on configs/config.yaml
> +  level: -4
Так у нас теперь log.Level это int. Опять получатся преобразования...

2023-09-22 10:47 UTC, nemca commented on README.md
> +# how to set logger level & format(text or json):
Добавил help

2023-09-22 10:47 UTC, nemca commented on go.mod
> +go 1.20
Установил 1.21

2023-09-22 10:47 UTC, nemca commented on internal/config/config.go
> +	// save DB pass from enviroment to Struct
Убрал

2023-09-22 10:48 UTC, nemca commented on configs/config.yaml
> +  level: -4
Да, пришлось писать функцию-парсер.

2023-09-22 17:12 UTC, nemca approved these changes

2023-09-22 17:12 UTC, merged