Add gorilla router and user handler
mixanemca/example-gorilla-rest-api pull request #5
Opened 2023-10-01 12:36 UTC by 0ylo

2023-10-01 12:53 UTC, nemca requested changes

2023-10-01 12:53 UTC, nemca commented on internal/config/config.go
> +		viper.AddConfigPath("../../configs")
Это зачем?

2023-10-01 12:53 UTC, nemca commented on internal/app/api/handler/v1/user.go
> +func (u *UsersController) GetUser(w http.ResponseWriter, r *http.Request) {
Может лучше `GetUserByID`?

2023-10-01 12:53 UTC, nemca commented on internal/app/app.go
> +func RunHandlers() {
Почему run? Что функция запускает?

2023-10-01 12:53 UTC, nemca commented on internal/app/app.go
> +func ShowEndpoints(w http.ResponseWriter, r *http.Request) {
Тут должен быть OpenAPI.

2023-10-01 12:53 UTC, nemca commented on internal/app/app.go
> +package api
Почему `api`, а не `app`?
И почему для обработчиков?
Мне кажется тут должна быть структура приложения, а уже в ней HTTP сервер, база и тд

2023-10-01 14:57 UTC, 0ylo commented on internal/config/config.go
> +		viper.AddConfigPath("../../configs")
дебаггер при запуске ищет не с корня, а с расположения мейн.го

2023-10-02 04:34 UTC, 0ylo commented on internal/app/app.go
> +package api
Взял за основу 
https://github.com/mixanemca/pdns-api/blob/main/internal/app/api/app.go
Но у нас наверно сильно проще все должно быть, хотя бы для начала наверно.

2023-10-02 07:24 UTC, nemca commented on internal/config/config.go
> +		viper.AddConfigPath("../../configs")
Может лучше дебагер настроить, чем такую бомбу тут оставлять?

2023-10-03 11:38 UTC, nemca requested changes

2023-10-03 11:38 UTC, nemca commented on internal/app/api/app.go
> +// ShowEndpoints is the temporary, while haven't swagger
Во-первых комментарий не сходится.
Во-вторых я имел в виду нормальный OpenAPI, автосгенерированный.
То есть лучше добавить этот URI после добавления OpenAPI и генерации документации.

2023-10-04 13:00 UTC, nemca requested changes

2023-10-04 13:00 UTC, nemca commented on models/entity/common.go
> +package entity
Кажется избыточным. Пакета `models` должно хватить

2023-10-04 13:00 UTC, nemca commented on internal/app/api/handler/v1/user.go
> +var Instance UserRepository = userService{
Ну хз. Странная сущность с областью видимости в целый пакет.
А как ее тестировать?
Может лучше сделать конструктор `NewUserRepository()`?
Или даже больше.
В app надо создавать репозиторий и сервис. Сперва репозиторий, примерно [так](https://github.com/zhashkevych/go-clean-architecture/blob/3bb8adb7e36f14ffc8d76c9325f22a5c179c9464/server/app.go#L36), а дальше [сервис](https://github.com/zhashkevych/go-clean-architecture/blob/3bb8adb7e36f14ffc8d76c9325f22a5c179c9464/server/app.go#L41).
То есть вся логика и поведение описывается в сервисе. При создании сервис принимает интерфейс репозитория и оперирует только методами. И получается, что в app мы можем создавать нужный нам репозиторий и пробрасывать его в сервис.
А вот тесты будут писаться на логику, то есть вокруг сервиса и вызова методов репозитория.
Тогда будет совершенно неважно где у тебя лежат пользователи - в базе, а памяти или вообще в файле.

2023-10-04 13:00 UTC, nemca commented on internal/app/api/handler/v1/user.go
> +func (u userService) CreateUser(w http.ResponseWriter, r *http.Request) {
А где тесты?

2023-10-04 13:00 UTC, nemca commented on internal/app/api/api.go
> +	http.Handle("/", router)
Не надо так.
В app надо завести HTTPServer, например [так](https://github.com/mixanemca/pdns-api/blob/e6503beeac97d24a417f5aab59c9b2911a5ad2c7/internal/app/api/app.go#L50).
А дальше запускать примерно [так](https://github.com/mixanemca/pdns-api/blob/e6503beeac97d24a417f5aab59c9b2911a5ad2c7/internal/app/api/app.go#L223).

2023-10-04 13:36 UTC, 0ylo commented on models/entity/common.go
> +package entity
Должно, это в горме все на этом держится, поэтому приходится делать еще 2 на запрос и на ответ

2023-10-04 13:41 UTC, nemca commented on models/entity/common.go
> +package entity
Что тебе мешает запросы и ответы в `models` деражть?

2023-10-05 07:48 UTC, nemca requested changes

2023-10-05 07:48 UTC, nemca commented on cmd/example-gorilla-rest-api/main.go
> +	apiApp := api.NewApp(*cfg, log)
```
a, err := app.New(cfg, log)
if err != nil {}
if err := a.Run(); err != nil {}
```

2023-10-05 07:48 UTC, nemca commented on cmd/example-gorilla-rest-api/main.go
> +		log.Fatalf("error occurred while reading config: %s\n", err.Error()) // TODO: change when external logger was added
Logger собирается ниже, так что тут можно и такой оставить.

2023-10-05 07:48 UTC, nemca commented on internal/app/api/api.go
> +	shutdownCtx, cancel := context.WithTimeout(context.Background(), time.Duration(5*time.Second))
```
time.Duration(5*time.Second)
```
хардкод, может вынести в конфиг?

2023-10-05 08:15 UTC, 0ylo commented on cmd/example-gorilla-rest-api/main.go
> +	apiApp := api.NewApp(*cfg, log)
конструктор не возвращает ошибку
Run метод пока тоже, стоит сейчас завести возврат ошибки или уже когда появится функционал возвращающий ошибку?

2023-10-05 08:34 UTC, nemca commented on cmd/example-gorilla-rest-api/main.go
> +	apiApp := api.NewApp(*cfg, log)
Лучше сразу.
Я вообще плохо отношусь к функциям без возврата ошибки, если в логике она может случиться.

2023-10-05 08:34 UTC, nemca commented on cmd/example-gorilla-rest-api/main.go
> +	apiApp := api.NewApp(*cfg, log)
Ну и да, я написал пример как раз с подсказкой, что надо дописывать возврат ошибки.

2023-10-15 10:55 UTC, nemca requested changes

2023-10-15 10:55 UTC, nemca commented on Makefile
> +.PHONY: swagger
`make doc` имхо круче

2023-10-15 10:55 UTC, nemca commented on internal/app/api/handler/v1/user_test.go
> +	r := NewUserRepository(db)
Выше `NewUserRepository()` не принимает аргументов

2023-10-15 10:55 UTC, nemca commented on internal/app/api/handler/v1/user.go
> +func NewUserRepository() *userService {
Какая-то путаница.
Вроде создается репозиторий, а возвращается сервис.

2023-10-15 10:55 UTC, nemca commented on models/common.go
> +type IDInfo struct {
Это зачем?

2023-10-28 07:05 UTC, 0ylo commented on models/common.go
> +type IDInfo struct {
Для возврата идентификатора созданной записи.
То есть создали юзера - вернулся айдишник созданного юзера - IDInfo как раз для возврата этого айдишника

2023-11-25 07:30 UTC, merged