Add sqlite in memory with repository pattern
mixanemca/example-gorilla-rest-api pull request #8
Opened 2024-01-04 16:41 UTC by 0ylo

2024-01-05 10:08 UTC, nemca requested changes

2024-01-05 10:08 UTC, nemca commented on internal/app/api/utils/validator.go
> +	_ = validate.RegisterTranslation("required", translate, func(ut ut.Translator) error {
Тут же обработка ошибки должна быть?
Я вот совсем не уверен, что валадатор создается в 100% случаев, так что конструктор должен возвращаться error последним значением.

2024-01-05 10:08 UTC, nemca commented on internal/storage/sqlite/sqlite.go
> +		log.Fatalf("filed to create sqlite connection %s", err.Error())
`logger` наверно же принятый, а не дефолтный `log`.

2024-01-05 10:08 UTC, nemca commented on internal/storage/postgres/pg.go
> +	logger.Info("connected to Postgres DB succsessfuly")
Почему не везде `logger`?

2024-01-05 10:08 UTC, nemca commented on internal/config/config.go
> +	fmt.Println(cfg)
Зачем это?
Если ты хочешь что-то выводить то делай это красиво и с описанием.

2024-01-05 10:08 UTC, nemca commented on internal/config/config.go
> +	SQLite   string = "sqlite"
Не смешивай константы со значениями и с iota

2024-01-05 10:08 UTC, nemca commented on internal/config/config.go
> +	SQLite   string = "sqlite"
Ну и я бы обозвал более полно, например `DBTypeSQLite` и получится `config.DBTypeSQLite`

2024-01-05 10:08 UTC, nemca commented on internal/app/app.go
> +		log.Fatal("field to sen any database type")
to sen?

2024-01-05 10:08 UTC, nemca commented on internal/app/app.go
> +	switch cfg.Database.DBType { // set database type
Комментарий странный. Что ты выставляешь? Наоборот же в зависимости от выставленной настройки в конфиге ты создаешь нужный репо.

2024-01-05 10:08 UTC, nemca commented on internal/storage/postgres/pg.go
> +func NewConnection(cfg config.Config, logger *slog.Logger) *pgxpool.Pool {
Нужно возвращать ошибку, если не получится создать пул.

2024-01-05 10:08 UTC, nemca commented on internal/app/app.go
> +		db := pg.NewConnection(cfg, logger)
А вот тут надо проверять ошибку, что пул создался.

2024-01-05 10:08 UTC, nemca commented on internal/app/app.go
> +	pg "github.com/mixanemca/example-gorilla-rest-api/internal/storage/postgres"
Почему оно сюда перенеслось?

2024-01-05 10:08 UTC, nemca commented on internal/app/app.go
> +	"log"
Этого пакета быть не должно

2024-01-05 10:08 UTC, nemca commented on internal/storage/sqlite/sqlite.go
> +	db, err := sql.Open("sqlite3", ":memory:") // memory placed
Почему именно в памяти?
И почему не DSN (connection string), как в PostgreSQL?

2024-01-05 10:08 UTC, nemca commented on internal/storage/sqlite/sqlite.go
> +	db, err := sql.Open("sqlite3", ":memory:") // memory placed
Ну и напрашиваются константы

2024-01-05 10:08 UTC, nemca commented on internal/app/api/handler/v1/user_pg.go
> +func NewUserRepositoryPg(db *pgxpool.Pool) *UserRepoPg {
И тут нет проверок на ошибку.

2024-01-05 10:08 UTC, nemca commented on internal/app/api/handler/v1/user_pg.go
> +		http.Error(w, "Invalid JSON", http.StatusBadRequest)
`err` не уходит в ответ, а значит будет сложно понять, что в запросе криво.

2024-01-05 10:08 UTC, nemca commented on internal/app/api/handler/v1/user_pg.go
> +		return
Почему просто `return` а не ошибка?

2024-01-05 10:08 UTC, nemca commented on internal/app/api/handler/v1/user_pg.go
> +	query := "UPDATE  users SET deleted_at=$1 WHERE id=$2;"
Пробел лишний

2024-01-07 08:58 UTC, 0ylo commented on internal/app/api/utils/validator.go
> +	_ = validate.RegisterTranslation("required", translate, func(ut ut.Translator) error {
в примерах пропускают, но согласен, логично обрабатывать, если функция возвращает

2024-01-07 10:32 UTC, 0ylo commented on internal/storage/sqlite/sqlite.go
> +	db, err := sql.Open("sqlite3", ":memory:") // memory placed
Ты просил именно инмемори, чтобы все работало без подключения к внешней БД.
Можем сделать в файле через  sql.Open("sqlite3", "./foo.db") - вторым параметром путь до файла. 

connection string не нужна - у нас же не внешняя база, или в памяти или файлом.

2024-03-11 13:34 UTC, merged